// Copyright (c) 2021, Adam Congdon <adam.congdon2@gmail.com>
// MIT License
using System;
using System.Diagnostics;
using System.IO;
using System.Text;
using System.Text.Json;
using VeeamHealthCheck.Shared;
using VeeamHealthCheck.Startup;

namespace VeeamHealthCheck.Functions.Monitor
{
    public class CVhcMonitorIntegration
    {
        private static string InstallDir =>
            Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData),
                "VeeamHealthCheck", "monitor");

        private static string ConfigPath => Path.Combine(InstallDir, "vhc-monitor.yaml");

        private static string ExeInstalledPath => Path.Combine(InstallDir, "vhc-monitor.exe");

        private static string ExeBundlePath =>
            Path.Combine(Path.GetDirectoryName(Environment.ProcessPath) ?? string.Empty, "vhc-monitor.exe");

        private static readonly string TaskName = "VHC Monitor";

        public static bool IsExePresentInBundle()
        {
            return File.Exists(ExeBundlePath);
        }

        public static bool IsInstalled()
        {
            return File.Exists(ExeInstalledPath);
        }

        public static bool IsTaskRegistered()
        {
            try
            {
                var (exitCode, stdout, _) = RunProcess("powershell",
                    "-NoProfile -Command \"Get-ScheduledTask -TaskName 'VHC Monitor' -ErrorAction SilentlyContinue | Select-Object -ExpandProperty TaskName\"");
                return exitCode == 0 && stdout.Contains("VHC Monitor");
            }
            catch (Exception ex)
            {
                CGlobals.Logger.Debug($"IsTaskRegistered check failed: {ex.Message}");
                return false;
            }
        }

        public static string GetInstalledVersion()
        {
            try
            {
                var (exitCode, stdout, _) = RunProcess(ExeInstalledPath, "--version");
                if (exitCode == 0 && !string.IsNullOrWhiteSpace(stdout))
                    return stdout.Trim();
            }
            catch (Exception ex)
            {
                CGlobals.Logger.Debug($"GetInstalledVersion failed: {ex.Message}");
            }
            return "unknown";
        }

        public static void GenerateConfig(string vbrServer, string username, string password,
            string notifType = "", string notifUrl = "", string minSeverity = "warning")
        {
            Directory.CreateDirectory(InstallDir);

            var sb = new StringBuilder();
            sb.AppendLine("# vhc-monitor configuration — generated by VeeamHealthCheck");
            sb.AppendLine("global:");
            sb.AppendLine("  timeout_seconds: 30");
            sb.AppendLine("  retry_count: 2");
            sb.AppendLine();
            sb.AppendLine("servers:");
            sb.AppendLine("  - name: vbr-primary");
            sb.AppendLine("    type: vbr");
            sb.AppendLine($"    url: \"https://{vbrServer}:9419\"");
            sb.AppendLine($"    username: \"{EscapeYaml(username)}\"");
            sb.AppendLine($"    password: \"{EscapeYaml(password)}\"");
            sb.AppendLine("    api_version: \"1.3-rev1\"");
            sb.AppendLine("    verify_ssl: false");
            sb.AppendLine();
            sb.AppendLine("output:");
            sb.AppendLine("  json_stdout: true");

            if (!string.IsNullOrWhiteSpace(notifUrl))
            {
                string webhookType = (notifType?.ToLower()) switch
                {
                    "teams" => "teams",
                    "slack" => "slack",
                    "pagerduty" => "pagerduty",
                    _ => "ntfy"
                };

                sb.AppendLine("  webhook:");
                sb.AppendLine($"    type: \"{webhookType}\"");
                sb.AppendLine($"    url: \"{EscapeYaml(notifUrl)}\"");
                sb.AppendLine($"    min_severity: \"{minSeverity}\"");
            }

            sb.AppendLine();
            sb.AppendLine("monitors:");
            sb.AppendLine("  repo_health:");
            sb.AppendLine("    enabled: true");
            sb.AppendLine("  retention:");
            sb.AppendLine("    enabled: true");
            sb.AppendLine("  worker_health:");
            sb.AppendLine("    enabled: true");

            File.WriteAllText(ConfigPath, sb.ToString(), Encoding.UTF8);
            CGlobals.Logger.Info($"vhc-monitor config written to {ConfigPath}", false);
        }

        public static void Install(string vbrServer, string username, string password,
            string notifType = "", string notifUrl = "", string minSeverity = "warning")
        {
            CGlobals.Logger.Info("Installing vhc-monitor...", false);

            // 1. Create install directory
            Directory.CreateDirectory(InstallDir);

            // 2. Copy exe
            File.Copy(ExeBundlePath, ExeInstalledPath, overwrite: true);
            CGlobals.Logger.Info($"Copied vhc-monitor.exe to {InstallDir}", false);

            // 3. Generate config
            GenerateConfig(vbrServer, username, password, notifType, notifUrl, minSeverity);

            // 4. Register scheduled task
            string ps1 = $@"
$action = New-ScheduledTaskAction -Execute ""{ExeInstalledPath}"" -Argument ""all --config `""{ConfigPath}`""""
$trigger = New-ScheduledTaskTrigger -RepetitionInterval (New-TimeSpan -Minutes 5) -Once -At (Get-Date)
$settings = New-ScheduledTaskSettingsSet -ExecutionTimeLimit (New-TimeSpan -Minutes 4) -StartWhenAvailable $true
Register-ScheduledTask -TaskName ""{TaskName}"" -Action $action -Trigger $trigger -Settings $settings -RunLevel Limited -Force
";
            var (exitCode, stdout, stderr) = RunProcess("powershell",
                $"-NoProfile -Command \"{ps1.Replace("\"", "\\\"")}\"", 30000);

            if (exitCode != 0)
            {
                CGlobals.Logger.Error($"Scheduled task registration failed (exit {exitCode}): {stderr}", false);
                // Try with encoded command as fallback
                string encoded = Convert.ToBase64String(Encoding.Unicode.GetBytes(ps1));
                var (exitCode2, _, stderr2) = RunProcess("powershell",
                    $"-NoProfile -EncodedCommand {encoded}", 30000);
                if (exitCode2 != 0)
                    CGlobals.Logger.Error($"Scheduled task registration fallback also failed: {stderr2}", false);
                else
                    CGlobals.Logger.Info("Scheduled task registered (via encoded command).", false);
            }
            else
            {
                CGlobals.Logger.Info("Scheduled task 'VHC Monitor' registered successfully.", false);
            }
        }

        public static void InstallFromVhcData(string notifType = "", string notifUrl = "",
            string minSeverity = "warning")
        {
            string server = CGlobals.VBRServerName;
            var creds = CredentialStore.Get(server);
            if (creds == null)
            {
                CGlobals.Logger.Warning($"No stored credentials for {server}. Cannot install vhc-monitor.", false);
                return;
            }
            Install(server, creds.Value.Username, creds.Value.Password, notifType, notifUrl, minSeverity);
        }

        public static (int exitCode, string output) RunNow()
        {
            CGlobals.Logger.Info("Running vhc-monitor on demand...", false);
            var (exitCode, stdout, stderr) = RunProcess(ExeInstalledPath,
                $"all --config \"{ConfigPath}\"", 120000);

            string combined = stdout;
            if (!string.IsNullOrWhiteSpace(stderr))
                combined += Environment.NewLine + stderr;

            CGlobals.Logger.Info($"vhc-monitor completed with exit code {exitCode}", false);
            return (exitCode, combined);
        }

        public static (bool success, string details) TestConnection()
        {
            var (exitCode, stdout, stderr) = RunProcess(ExeInstalledPath,
                $"test-connection --config \"{ConfigPath}\"", 30000);

            string details = stdout;
            if (!string.IsNullOrWhiteSpace(stderr))
                details += Environment.NewLine + stderr;

            return (exitCode == 0, details);
        }

        public static void Uninstall()
        {
            CGlobals.Logger.Info("Removing VHC Monitor scheduled task...", false);
            try
            {
                RunProcess("powershell",
                    "-NoProfile -Command \"Unregister-ScheduledTask -TaskName 'VHC Monitor' -Confirm:$false -ErrorAction SilentlyContinue\"",
                    15000);
                CGlobals.Logger.Info("VHC Monitor scheduled task removed.", false);
            }
            catch (Exception ex)
            {
                CGlobals.Logger.Error($"Failed to remove scheduled task: {ex.Message}", false);
            }
        }

        public static MonitorLastRunStatus GetLastRunStatus()
        {
            string statePath = Path.Combine(InstallDir, "veeam-monitor-state.json");
            if (!File.Exists(statePath))
                return null;

            try
            {
                string json = File.ReadAllText(statePath);
                using var doc = JsonDocument.Parse(json);
                var root = doc.RootElement;

                var status = new MonitorLastRunStatus();

                if (root.TryGetProperty("last_run", out var lastRunProp))
                {
                    if (lastRunProp.ValueKind == JsonValueKind.String &&
                        DateTime.TryParse(lastRunProp.GetString(), out var ts))
                    {
                        status.Timestamp = ts;
                    }
                }

                if (root.TryGetProperty("summary", out var summaryProp) &&
                    summaryProp.ValueKind == JsonValueKind.String)
                {
                    status.Summary = summaryProp.GetString() ?? string.Empty;
                }

                if (root.TryGetProperty("finding_count", out var countProp) &&
                    countProp.ValueKind == JsonValueKind.Number)
                {
                    status.FindingCount = countProp.GetInt32();
                }

                return status;
            }
            catch (Exception ex)
            {
                CGlobals.Logger.Debug($"Failed to parse monitor state file: {ex.Message}");
                return null;
            }
        }

        private static (int exitCode, string stdout, string stderr) RunProcess(string exe, string args,
            int timeoutMs = 30000)
        {
            var psi = new ProcessStartInfo
            {
                FileName = exe,
                Arguments = args,
                RedirectStandardOutput = true,
                RedirectStandardError = true,
                UseShellExecute = false,
                CreateNoWindow = true
            };

            using var process = new Process { StartInfo = psi };
            var stdoutSb = new StringBuilder();
            var stderrSb = new StringBuilder();

            process.OutputDataReceived += (_, e) => { if (e.Data != null) stdoutSb.AppendLine(e.Data); };
            process.ErrorDataReceived += (_, e) => { if (e.Data != null) stderrSb.AppendLine(e.Data); };

            process.Start();
            process.BeginOutputReadLine();
            process.BeginErrorReadLine();

            if (!process.WaitForExit(timeoutMs))
            {
                try { process.Kill(true); }
                catch { /* best effort */ }
                CGlobals.Logger.Warning($"Process timed out after {timeoutMs}ms: {exe} {args}", false);
                return (-1, stdoutSb.ToString(), "Process timed out");
            }

            return (process.ExitCode, stdoutSb.ToString(), stderrSb.ToString());
        }

        private static string EscapeYaml(string value)
        {
            if (string.IsNullOrEmpty(value)) return value;
            return value.Replace("\\", "\\\\").Replace("\"", "\\\"");
        }
    }
}
