using System;
using System.IO;
using System.Linq;
using VeeamHealthCheck.Functions.Reporting.CsvHandlers;
using VhcXTests.TestData;
using Xunit;

namespace VhcXTests.Functions.Reporting.CsvHandlers
{
    /// <summary>
    /// Tests for CCsvParser CSV file parsing functionality.
    /// Uses test data generated by VbrCsvSampleGenerator.
    /// </summary>
    [Trait("Category", "CsvParsing")]
    public class CCsvParser_TEST : IDisposable
    {
        private readonly string _testDataDir;
        private readonly string _vbrDir;

        public CCsvParser_TEST()
        {
            // Create test data directory with sample CSV files
            _testDataDir = Path.Combine(Path.GetTempPath(), "VhcCsvParserTests_" + Guid.NewGuid().ToString());
            _vbrDir = VbrCsvSampleGenerator.CreateTestDataDirectory(_testDataDir);
        }

        public void Dispose()
        {
            VbrCsvSampleGenerator.CleanupTestDirectory(_testDataDir);
        }

        #region Constructor Tests

        [Fact]
        public void CsvParser_DefaultConstructor_UsesGlobalPath()
        {
            // Note: This test verifies the default constructor exists
            // In production, it uses CVariables.vbrDir
            var parser = new CCsvParser();
            Assert.NotNull(parser);
        }

        [Fact]
        public void CsvParser_PathConstructor_UsesProvidedPath()
        {
            var parser = new CCsvParser(_vbrDir);
            Assert.NotNull(parser);
        }

        #endregion

        #region Archive Tier Tests

        [Fact]
        public void ArchiveTierCsvParser_ValidFile_ReturnsRecords()
        {
            var parser = new CCsvParser(_vbrDir);
            var result = parser.ArchiveTierCsvParser();

            Assert.NotNull(result);
            var records = result.ToList();
            Assert.Single(records);
        }

        [Fact]
        public void GetDynamicArchiveTier_ValidFile_ReturnsRecords()
        {
            var parser = new CCsvParser(_vbrDir);
            var result = parser.GetDynamicArchiveTier();

            Assert.NotNull(result);
            Assert.NotEmpty(result);
        }

        #endregion

        #region vbrinfo.csv Tests

        [Fact]
        public void GetDynamicVbrInfo_ValidFile_ReturnsRecords()
        {
            var parser = new CCsvParser(_vbrDir);
            var result = parser.GetDynamicVbrInfo();

            Assert.NotNull(result);
            var records = result.ToList();
            Assert.Single(records);
        }

        [Fact]
        public void GetDynamicVbrInfo_ValidFile_ContainsVersion()
        {
            var parser = new CCsvParser(_vbrDir);
            var result = parser.GetDynamicVbrInfo().ToList();

            Assert.Contains(result, r => r.version == "12.0.0.1420");
        }

        [Fact]
        public void GetDynamicVbrInfo_ValidFile_ContainsMfaField()
        {
            var parser = new CCsvParser(_vbrDir);
            var result = parser.GetDynamicVbrInfo().ToList();

            Assert.Contains(result, r => r.mfa == "True");
        }

        [Fact]
        public void GetDynamicVbrInfo_NoFile_ReturnsEmpty()
        {
            var emptyDir = Path.Combine(_testDataDir, "empty");
            Directory.CreateDirectory(emptyDir);

            var parser = new CCsvParser(emptyDir);
            var result = parser.GetDynamicVbrInfo();

            Assert.NotNull(result);
            Assert.Empty(result);
        }

        #endregion

        #region Servers.csv Tests

        [Fact]
        public void ServerCsvParser_ValidFile_ReturnsRecords()
        {
            var parser = new CCsvParser(_vbrDir);
            var result = parser.ServerCsvParser();

            Assert.NotNull(result);
            var records = result.ToList();
            Assert.Equal(3, records.Count);
        }

        [Fact]
        public void ServerCsvParser_NoFile_ReturnsEmpty()
        {
            var emptyDir = Path.Combine(_testDataDir, "empty_servers");
            Directory.CreateDirectory(emptyDir);

            var parser = new CCsvParser(emptyDir);
            var result = parser.ServerCsvParser();

            Assert.Empty(result);
        }

        #endregion

        #region Proxies.csv Tests

        [Fact]
        public void ProxyCsvParser_ValidFile_ReturnsRecords()
        {
            var parser = new CCsvParser(_vbrDir);
            var result = parser.ProxyCsvParser();

            Assert.NotNull(result);
            var records = result.ToList();
            Assert.Equal(2, records.Count);
        }

        [Fact]
        public void ProxyCsvParser_ValidFile_ContainsExpectedFields()
        {
            var parser = new CCsvParser(_vbrDir);
            var result = parser.ProxyCsvParser().ToList();

            Assert.Contains(result, p => p.Name == "Proxy-01");
            Assert.Contains(result, p => p.MaxTasksCount == "4");
        }

        [Fact]
        public void ProxyCsvParser_NoFile_ReturnsEmpty()
        {
            var emptyDir = Path.Combine(_testDataDir, "empty_proxy");
            Directory.CreateDirectory(emptyDir);

            var parser = new CCsvParser(emptyDir);
            var result = parser.ProxyCsvParser();

            Assert.Empty(result);
        }

        #endregion

        #region Repositories.csv Tests

        [Fact]
        public void RepoCsvParser_ValidFile_ReturnsRecords()
        {
            var parser = new CCsvParser(_vbrDir);
            var result = parser.RepoCsvParser();

            Assert.NotNull(result);
            var records = result.ToList();
            Assert.Equal(2, records.Count);
        }

        [Fact]
        public void GetDynamicRepo_ValidFile_ReturnsRecords()
        {
            var parser = new CCsvParser(_vbrDir);
            var result = parser.GetDynamicRepo();

            Assert.NotNull(result);
            var records = result.ToList();
            Assert.Equal(2, records.Count);
        }

        [Fact]
        public void GetDynamicRepo_ValidFile_ContainsImmutabilityField()
        {
            var parser = new CCsvParser(_vbrDir);
            var result = parser.GetDynamicRepo().ToList();

            Assert.Contains(result, r => r.isimmutabilitysupported == "True");
            Assert.Contains(result, r => r.isimmutabilitysupported == "False");
        }

        #endregion

        #region Jobs.csv Tests

        [Fact]
        public void JobCsvParser_ValidFile_ReturnsRecords()
        {
            var parser = new CCsvParser(_vbrDir);
            var result = parser.JobCsvParser();

            Assert.NotNull(result);
            var records = result.ToList();
            Assert.Equal(3, records.Count);
        }

        [Fact]
        public void JobCsvParser_BackupCopyWorkerRow_IsNotReturnedAsAJob()
        {
            VbrCsvSampleGenerator.CreateCsvFile(_vbrDir, "_Jobs.csv", VbrCsvSampleGenerator.GenerateJobsWithBackupCopyWorker());
            var parser = new CCsvParser(_vbrDir);

            var jobs = parser.JobCsvParser().ToList();

            Assert.Equal(new[] { "CopyJobA", "SourceJobA - Nutanix Backup" }, jobs.Select(j => j.Name).ToArray());
            Assert.DoesNotContain(jobs, j => j.JobType == "SimpleBackupCopyParentWorker");
        }

        [Fact]
        public void JobCsvParser_BackupCopyWorkerRow_AddsItsOnDiskSizeToTheParent()
        {
            VbrCsvSampleGenerator.CreateCsvFile(_vbrDir, "_Jobs.csv", VbrCsvSampleGenerator.GenerateJobsWithBackupCopyWorker());
            var parser = new CCsvParser(_vbrDir);

            var jobs = parser.JobCsvParser().ToList();

            Assert.Equal(35.25, jobs.Single(j => j.Name == "CopyJobA").OnDiskGB);
            Assert.Equal(40, jobs.Single(j => j.Name == "SourceJobA - Nutanix Backup").OnDiskGB);
        }

        [Fact]
        public void JobCsvParser_BackupCopyWorkerWithoutParentRow_IsKept()
        {
            VbrCsvSampleGenerator.CreateCsvFile(_vbrDir, "_Jobs.csv", VbrCsvSampleGenerator.GenerateJobsWithBackupCopyWorkerAndNoParent());
            var parser = new CCsvParser(_vbrDir);

            var jobs = parser.JobCsvParser().ToList();

            var kept = Assert.Single(jobs);
            Assert.Equal("SimpleBackupCopyParentWorker", kept.JobType);
            Assert.Equal(25.25, kept.OnDiskGB);
        }

        [Fact]
        public void GetDynamicJobInfo_BackupCopyWorkerRow_StaysInTheRawCsv()
        {
            VbrCsvSampleGenerator.CreateCsvFile(_vbrDir, "_Jobs.csv", VbrCsvSampleGenerator.GenerateJobsWithBackupCopyWorker());
            var parser = new CCsvParser(_vbrDir);

            Assert.Equal(3, parser.GetDynamicJobInfo().Count());
        }

        [Fact]
        public void GetDynamicJobInfo_ValidFile_ReturnsRecords()
        {
            var parser = new CCsvParser(_vbrDir);
            var result = parser.GetDynamicJobInfo();

            Assert.NotNull(result);
            var records = result.ToList();
            Assert.Equal(3, records.Count);
        }

        [Fact]
        public void GetDynamicJobInfo_ContainsEncryptionInfo()
        {
            var parser = new CCsvParser(_vbrDir);
            var result = parser.GetDynamicJobInfo().ToList();

            // One job has no encryption (all zeros), two have encryption keys
            Assert.Contains(result, j => j.pwdkeyid == "00000000-0000-0000-0000-000000000000");
            Assert.Contains(result, j => j.pwdkeyid != "00000000-0000-0000-0000-000000000000");
        }

        #endregion

        #region SOBR Tests

        [Fact]
        public void SobrCsvParser_ValidFile_ReturnsRecords()
        {
            var parser = new CCsvParser(_vbrDir);
            var result = parser.SobrCsvParser();

            Assert.NotNull(result);
            var records = result.ToList();
            Assert.Equal(2, records.Count);
        }

        [Fact]
        public void SobrExtParser_ValidFile_ReturnsRecords()
        {
            var parser = new CCsvParser(_vbrDir);
            var result = parser.SobrExtParser();

            Assert.NotNull(result);
            var records = result.ToList();
            Assert.Equal(2, records.Count);
        }

        [Fact]
        public void GetDynamicSobr_ValidFile_ReturnsRecords()
        {
            var parser = new CCsvParser(_vbrDir);
            var result = parser.GetDynamicSobr();

            Assert.NotNull(result);
            Assert.NotEmpty(result);
        }

        [Fact]
        public void GetDynamicSobrExt_ValidFile_ReturnsRecords()
        {
            var parser = new CCsvParser(_vbrDir);
            var result = parser.GetDynamicSobrExt();

            Assert.NotNull(result);
            Assert.NotEmpty(result);
        }

        #endregion

        #region License Tests

        [Fact]
        public void GetDynamicLicenseCsv_ValidFile_ReturnsRecords()
        {
            var parser = new CCsvParser(_vbrDir);
            var result = parser.GetDynamicLicenseCsv();

            Assert.NotNull(result);
            var records = result.ToList();
            Assert.Single(records);
        }

        #endregion

        #region Config Backup Tests

        [Fact]
        public void ConfigBackupCsvParser_ValidFile_ReturnsRecords()
        {
            var parser = new CCsvParser(_vbrDir);
            var result = parser.ConfigBackupCsvParser();

            Assert.NotNull(result);
            var records = result.ToList();
            Assert.Single(records);
        }

        [Fact]
        public void GetDynamincConfigBackup_ValidFile_ReturnsRecords()
        {
            var parser = new CCsvParser(_vbrDir);
            var result = parser.GetDynamincConfigBackup();

            Assert.NotNull(result);
            Assert.NotEmpty(result);
        }

        #endregion

        #region Traffic Rules Tests

        [Fact]
        public void NetTrafficCsvParser_ValidFile_ReturnsRecords()
        {
            var parser = new CCsvParser(_vbrDir);
            var result = parser.NetTrafficCsvParser();

            Assert.NotNull(result);
            var records = result.ToList();
            Assert.Equal(2, records.Count);
        }

        [Fact]
        public void GetDynamincNetRules_ValidFile_ContainsEncryptionField()
        {
            var parser = new CCsvParser(_vbrDir);
            var result = parser.GetDynamincNetRules().ToList();

            Assert.Contains(result, r => r.encryptionenabled == "True");
        }

        #endregion

        #region Registry Options Tests

        [Fact]
        public void RegOptionsCsvParser_ValidFile_ReturnsRecords()
        {
            var parser = new CCsvParser(_vbrDir);
            var result = parser.RegOptionsCsvParser();

            Assert.NotNull(result);
            var records = result.ToList();
            Assert.Equal(2, records.Count);
        }

        #endregion

        #region Protected VM Tests

        [Fact]
        public void ViProtectedReader_ValidFile_ReturnsRecords()
        {
            var parser = new CCsvParser(_vbrDir);
            var result = parser.ViProtectedReader();

            Assert.NotNull(result);
            var records = result.ToList();
            Assert.Equal(2, records.Count);
        }

        [Fact]
        public void ViUnProtectedReader_ValidFile_ReturnsRecords()
        {
            var parser = new CCsvParser(_vbrDir);
            var result = parser.ViUnProtectedReader();

            Assert.NotNull(result);
            var records = result.ToList();
            Assert.Equal(2, records.Count);
        }

        #endregion

        #region Edge Cases

        [Fact]
        public void CsvParser_EmptyDirectory_HandlesGracefully()
        {
            var emptyDir = Path.Combine(_testDataDir, "completely_empty");
            Directory.CreateDirectory(emptyDir);

            var parser = new CCsvParser(emptyDir);

            // All parsers should return empty for missing files
            Assert.Empty(parser.ServerCsvParser());
            Assert.Empty(parser.ProxyCsvParser());
            Assert.Empty(parser.RepoCsvParser());
            Assert.Empty(parser.SobrCsvParser());
        }

        [Fact]
        public void CsvParser_NonExistentDirectory_HandlesGracefully()
        {
            var nonExistentDir = Path.Combine(_testDataDir, "does_not_exist");

            var parser = new CCsvParser(nonExistentDir);

            // Should not throw, should return empty
            Assert.Empty(parser.ServerCsvParser());
        }

        [Fact]
        public void CsvParser_EmptyFile_ReturnsNullOrEmpty()
        {
            var emptyFileDir = Path.Combine(_testDataDir, "empty_files");
            Directory.CreateDirectory(emptyFileDir);

            // Create empty CSV (headers only)
            VbrCsvSampleGenerator.CreateCsvFile(emptyFileDir, "Servers.csv", VbrCsvSampleGenerator.GenerateEmptyServers());

            var parser = new CCsvParser(emptyFileDir);
            var result = parser.ServerCsvParser();

            // Empty file should return empty enumerable or null
            Assert.True(result == null || !result.Any());
        }

        #endregion

        #region NAS Share Size Tests

        [Fact]
        public void GetDynamicNasShareSize_V12CombinedLine_ParsesAllFields()
        {
            // v12 format: single combined line, no ParentServerID column
            var csv =
                "FileShareID,FileShareType,TotalShareSize,TotalFilesCount,TotalFoldersCount," +
                "AvgIncrementSize,AvgFilesCountPerInc,AvgFoldersCountPerInc," +
                "FileProxy,ProxyIDs,BackupMode,CacheRepository,BackupIOControlLevel\r\n" +
                "share-001,NFS,41710468504,100000,5000,1048576,200,10," +
                "proxy01,{proxy-id-001},Direct,repo01,3\r\n";

            VbrCsvSampleGenerator.CreateCsvFile(_vbrDir, "NasSharesize.csv", csv);

            var parser = new CCsvParser(_vbrDir);
            var results = parser.GetDynamicNasShareSize().ToList();

            Assert.Single(results);
            Assert.Equal("share-001", results[0].FileShareID);
            Assert.Equal("41710468504", results[0].TotalShareSize);
            Assert.Equal("proxy01", results[0].FileProxy);
            Assert.Null(results[0].ParentServerID);
        }

        [Fact]
        public void GetDynamicNasShareSize_V13ParentChildJoined_ParsesAllFields()
        {
            // v13 format: child row already merged with parent fields (join done in PS1)
            var csv =
                "FileShareID,ParentServerID,FileShareType,TotalShareSize,TotalFilesCount,TotalFoldersCount," +
                "AvgIncrementSize,AvgFilesCountPerInc,AvgFoldersCountPerInc," +
                "FileProxy,ProxyIDs,BackupMode,CacheRepository,BackupIOControlLevel\r\n" +
                "child-001,parent-001,SMB,20971520,50000,2500,524288,100,5," +
                "proxy02,{proxy-id-002},Manual,repo02,2\r\n";

            VbrCsvSampleGenerator.CreateCsvFile(_vbrDir, "NasSharesize.csv", csv);

            var parser = new CCsvParser(_vbrDir);
            var results = parser.GetDynamicNasShareSize().ToList();

            Assert.Single(results);
            Assert.Equal("child-001", results[0].FileShareID);
            Assert.Equal("parent-001", results[0].ParentServerID);
            Assert.Equal("20971520", results[0].TotalShareSize);
            Assert.Equal("proxy02", results[0].FileProxy);
            Assert.Equal("Manual", results[0].BackupMode);
        }

        #endregion

        #region CCsvReader Tests

        [Fact]
        public void FileFinder_InvalidPath_ReturnsNull()
        {
            var reader = new CCsvReader();
            var result = reader.FileFinder("", "");

            Assert.Null(result);
        }

        [Fact]
        public void FileFinder_NonExistentFile_ReturnsNull()
        {
            var reader = new CCsvReader();
            var result = reader.FileFinder("nonexistent.csv", _vbrDir);

            Assert.Null(result);
        }

        #endregion
    }
}
