//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeeamHealthCheck.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class VhcResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VhcResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VeeamHealthCheck.Resources.VhcResources", typeof(VhcResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept Terms.
        /// </summary>
        public static string GuiAcceptButton {
            get {
                return ResourceManager.GetString("GuiAcceptButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string GuiImportButton {
            get {
                return ResourceManager.GetString("GuiImportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * If opted to remove sensitive data types, only HTML report will be cleansed. See: .
        /// </summary>
        public static string GuiInstCaveat1 {
            get {
                return ResourceManager.GetString("GuiInstCaveat1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;** Note, in larger environments, this tool can take up to 3 hours to complete.&quot;.
        /// </summary>
        public static string GuiInstCaveat2 {
            get {
                return ResourceManager.GetString("GuiInstCaveat2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructions:.
        /// </summary>
        public static string GuiInstHeader {
            get {
                return ResourceManager.GetString("GuiInstHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Accept Terms.
        /// </summary>
        public static string GuiInstLine1 {
            get {
                return ResourceManager.GetString("GuiInstLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Click RUN.
        /// </summary>
        public static string GuiInstLine2 {
            get {
                return ResourceManager.GetString("GuiInstLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Upon completion, Windows Explorer will open to the output directory. (If enabled, HTML report will be shown).
        /// </summary>
        public static string GuiInstLine3 {
            get {
                return ResourceManager.GetString("GuiInstLine3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4. Review the report as desired.
        /// </summary>
        public static string GuiInstLine4 {
            get {
                return ResourceManager.GetString("GuiInstLine4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5. Capture output from C:\temp\vHC* - or whichever directory was specified..
        /// </summary>
        public static string GuiInstLine5 {
            get {
                return ResourceManager.GetString("GuiInstLine5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6. Notify your Veeam SE and/or send them the results for review.
        /// </summary>
        public static string GuiInstLine6 {
            get {
                return ResourceManager.GetString("GuiInstLine6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options:.
        /// </summary>
        public static string GuiOptionsHeader {
            get {
                return ResourceManager.GetString("GuiOptionsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output path.
        /// </summary>
        public static string GuiOutPath {
            get {
                return ResourceManager.GetString("GuiOutPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        public static string GuiRunButton {
            get {
                return ResourceManager.GetString("GuiRunButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove sensitive data types from report.
        /// </summary>
        public static string GuiSensData {
            get {
                return ResourceManager.GetString("GuiSensData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show files on completion.
        /// </summary>
        public static string GuiShowFiles {
            get {
                return ResourceManager.GetString("GuiShowFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show HTML report upon completion.
        /// </summary>
        public static string GuiShowHtml {
            get {
                return ResourceManager.GetString("GuiShowHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health Check Report.
        /// </summary>
        public static string HtmlHeader {
            get {
                return ResourceManager.GetString("HtmlHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - This report provides data and insight into your Veeam Backup and Replication (VBR) deployment. The information provided here is intended to be used in collaboration with your Veeam representative..
        /// </summary>
        public static string HtmlIntroLine1 {
            get {
                return ResourceManager.GetString("HtmlIntroLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - The raw data is captured in CSV format and is accessible locally in the Export Folder. CSV will let you manipulate the data in tools such as Excel..
        /// </summary>
        public static string HtmlIntroLine2 {
            get {
                return ResourceManager.GetString("HtmlIntroLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Additional information on individual job sessions can be found in the &lt;a href=&quot;C:\temp\vHC\JobSessionReports&quot;&gt; output folder at C:\temp\vHC\JobSessionReports.
        /// </summary>
        public static string HtmlIntroLine3 {
            get {
                return ResourceManager.GetString("HtmlIntroLine3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - NOTE: During mouseover, a tool tip may appear containing explanatory data of the table header or data column..
        /// </summary>
        public static string HtmlIntroLine4 {
            get {
                return ResourceManager.GetString("HtmlIntroLine4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - \bNOTE: The tool you ran to generate this report is completely self-contained, does not ‘phone-home’ and was only executed on your Veeam Backup and Replication server. It queries the VBR database, registry, configuration and log files. It does not require access to vCenter or any other infrastructure..
        /// </summary>
        public static string HtmlIntroLine5 {
            get {
                return ResourceManager.GetString("HtmlIntroLine5", resourceCulture);
            }
        }
    }
}
