//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeeamHealthCheck {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VeeamHealthCheck.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept Terms.
        /// </summary>
        internal static string GuiAcceptButton {
            get {
                return ResourceManager.GetString("GuiAcceptButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string GuiCaveat1Part2 {
            get {
                return ResourceManager.GetString("GuiCaveat1Part2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        internal static string GuiImportButton {
            get {
                return ResourceManager.GetString("GuiImportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * If opted to remove sensitive data types, only HTML report will be cleansed. See: .
        /// </summary>
        internal static string GuiInstCaveat1 {
            get {
                return ResourceManager.GetString("GuiInstCaveat1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;** Note, in larger environments, this tool can take up to 3 hours to complete.&quot;.
        /// </summary>
        internal static string GuiInstCaveat2 {
            get {
                return ResourceManager.GetString("GuiInstCaveat2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructions:.
        /// </summary>
        internal static string GuiInstHeader {
            get {
                return ResourceManager.GetString("GuiInstHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Accept Terms.
        /// </summary>
        internal static string GuiInstLine1 {
            get {
                return ResourceManager.GetString("GuiInstLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Click RUN.
        /// </summary>
        internal static string GuiInstLine2 {
            get {
                return ResourceManager.GetString("GuiInstLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Upon completion, Windows Explorer will open to the output directory. (If enabled, HTML report will be shown).
        /// </summary>
        internal static string GuiInstLine3 {
            get {
                return ResourceManager.GetString("GuiInstLine3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4. Review the report as desired.
        /// </summary>
        internal static string GuiInstLine4 {
            get {
                return ResourceManager.GetString("GuiInstLine4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5. Capture output from C:\temp\vHC* - or whichever directory was specified..
        /// </summary>
        internal static string GuiInstLine5 {
            get {
                return ResourceManager.GetString("GuiInstLine5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6. Notify your Veeam SE and/or send them the results for review.
        /// </summary>
        internal static string GuiInstLine6 {
            get {
                return ResourceManager.GetString("GuiInstLine6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options:.
        /// </summary>
        internal static string GuiOptionsHeader {
            get {
                return ResourceManager.GetString("GuiOptionsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output path.
        /// </summary>
        internal static string GuiOutPath {
            get {
                return ResourceManager.GetString("GuiOutPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        internal static string GuiRunButton {
            get {
                return ResourceManager.GetString("GuiRunButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove sensitive data types from report.
        /// </summary>
        internal static string GuiSensData {
            get {
                return ResourceManager.GetString("GuiSensData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string GuiSensDataString {
            get {
                return ResourceManager.GetString("GuiSensDataString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show files on completion.
        /// </summary>
        internal static string GuiShowFiles {
            get {
                return ResourceManager.GetString("GuiShowFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show HTML report upon completion.
        /// </summary>
        internal static string GuiShowHtml {
            get {
                return ResourceManager.GetString("GuiShowHtml", resourceCulture);
            }
        }
    }
}
