name: Semgrep Scan

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches:
      - master
      - dev

jobs:
  semgrep:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2

    - name: Set up Python
      uses: actions/setup-python@e9aba2c848f5ebd159c070c61ea2c4e2b122355e # v2
      with:
        python-version: '3.x'

    - name: Install Semgrep
      run: pip install semgrep

    - name: Run Semgrep
      run: semgrep --config auto --error

    - name: SemGrep SupplyChain
      run: semgrep --config "p/supply-chain"
