name: Virus Scan

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  virus-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install ClamAV
      run: sudo apt-get update && sudo apt-get install -y clamav clamav-daemon

    - name: Update ClamAV database
      run: sudo freshclam

    - name: Scan repository for viruses
      run: sudo clamscan -r --bell -i .